name: CD

on:
  workflow_call:
    inputs:
      commit:
        type: string
        description: 'Short SHA of commit to build (6 char)'
        required: false
      appenv:
        type: string
        description: 'Environment to be deployed on'
        required: true

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit }}
          fetch-depth: 0

      - name: Set short_sha
        id: vars
        run: |
          if [[ "${{ inputs.commit }}" == "" ]]; then
            echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          else
            echo "short_sha=${{ inputs.commit }}" >> $GITHUB_ENV
          fi
          echo "Commit to deploy: ${{ env.short_sha }}"