name: 1. CI

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: 'Full SHA of commit to be built'
        required: false

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  CI:
    uses: bz-services/Testing/.github/workflows/build-and-push-image.yaml@main
    with:
      commit: ${{ inputs.commit }}