name: 2. CICD (DEV)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  CI:
    uses: bz-services/Testing/.github/workflows/build-and-push-image.yaml@main

  CD:
    uses: bz-services/Testing/.github/workflows/deploy-to-ecs.yaml@main
    needs: CI
    with:
      appenv: dev
