name: hotfix

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: 'Short SHA of commit to build (6 char)'
        required: false

jobs:
  Hotfix-Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set short_sha
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: short_sha
        run: |
          echo "short_sha: ${{ env.short_sha }}"

      - name: cat file
        run: |
          cat test.txt





