name: PR

on:
  pull_request:
    branches: [ main ]
jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cat file
        run: |
          cat test.txt