name: 5. CD (PROD)

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: 'Full SHA of commit to be deployed'
        required: false

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  cd:
    uses: bz-services/Testing/.github/workflows/deploy-to-ecs.yaml@main
    needs: ci
    with:
      commit: ${{ inputs.commit }}
      appenv: prod