name: CD (STAGING)

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: 'Full SHA of commit to be deployed'
        required: false

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  cd:
    uses: bz-services/workflows-jobs/deploy-to-ecs.yaml@main
    with:
      commit: ${{ inputs.commit }}
      appenv: staging