name: STAGING

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: 'Short SHA of commit to deploy (6 char)'
        required: false

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ci:
    uses: bz-services/Testing/.github/workflows/ci.yaml@main
    with:
      commit: ${{ inputs.commit }}
    secrets: inherit

  cd:
    uses: bz-services/Testing/.github/workflows/cd.yaml@main
    needs: ci
    with:
      commit: ${{ inputs.commit }}
      appenv: staging
    secrets: inherit